### ISSUE TITLE
supporting part of RISC-V instruction set? Which part?

### ISSUE THREAD

**Issue by poweihuang17** [SI-RISCV/e200_opensource#1]
hi bob,
Could I ask you which parts of RISC-V instruction set are you supporting?
I guess it's written in document, but it might be better to put it on the readme.

**Comment by zhenbohu** [comment]
Hi, Powei

Please check the Table-1 from e200_opensource/doc/Hummingbird_E200_Series_Core_SoC_Introduction.pdf as the golden reference, for example, the E205 core support RV32IMAC, E205fd support RV32IMAFDC. And also please check the revision history of doc, sometimes it may changes.

A soft remind, current version of repo is an earlier-test version, I will upload the official release version soon. Please clone the official version then if you want to use it. 

Thanks 
Bob

**Comment by zhenbohu** [comment]
Hi, Powei

The 1st official release have been uploaded to Github now. Please check it.

Thanks
Bob

**Comment by poweihuang17** [comment]
Bob,
Thanks for your notification. I will check that and close this issue. Do you mind if we put your work into bi-weekly news for our next series 10/26?

**Comment by zhenbohu** [comment]
Sure，no problem, i will be my honor.

**Comment by poweihuang17** [comment]
nice.
