### ISSUE TITLE
关于e200_opensource协处理器模块EAI

### ISSUE THREAD

**Issue by albertcity** [SI-RISCV/e200_opensource#12]
亲爱的开发者们：
	您好！
        首先，我为在这里写这封信而感到抱歉，但是我们实在不知道要怎么联系你们，写给胡老师邮箱的信也一直没有收到回复。
	我是中国科学技术大学嵌入式实验室的研究生。目前我们实验室对RISC-V处理器比较感兴趣，因此组成了一个小组（四人）来研究学习一下。我们选定了国内的开源e200_opensource来作为研究对象，并且希望能在其中加入协处理器模块。我们每人都买了您所著的《手把手教你设计CPU---RISC_V处理器》，并且已经对照上边进行了大约四个周的学习。然而我们发现e200_opensource里，协处理器以及它的通信模块EAI都是缺省的，这使得我们难以开展下一步学习计划。
	由于我们都是研一的新生，之前也没有接触过这方面的内容，水平有限，因此我们诚挚地希望您能提供协处理器EAI的相关代码。如果方便的话，也希望能提供协处理器的源码，这将对我们有巨大的指导作用。
	十分感谢您能阅读这封信，我保证以上信息都是真实有效的，我们希望能得到您的帮助！以下是我的联系方式：yiqi@mail.ustc.edu.cn,十分希望能收到您的回信！
	祝好。

**Comment by AlexChenzixuan** [comment]
你好，我也是在做risc-v指令集处理器的一名研究生，希望能交个好友，可以一起讨论下。 微信：17326098347
