### ISSUE TITLE
端口名后缀

### ISSUE THREAD

**Issue by kezhou2** [SI-RISCV/e200_opensource#2]
_ival, _oval,_oe,_ie,_pue,_ds这些后缀分别是什么意思？

**Comment by vowstar** [comment]
@kezhou2 

* ival: input value, 输入值
* oval: output value, 输出值
* oe: output enable, 输出使能
* ie: input enable, 输入使能
* pue: pull up enable, 上拉使能
* ds: driving selector, 驱动强度(电流)选择
