### ISSUE TITLE
English language toolchain host

### ISSUE THREAD

**Issue by SKuRGe911** [SI-RISCV/e200_opensource#20]
Could you please upload your toolchain to a another server that is english. Ive tried to log into that baidu server but it needs member ship and i cant figure out how to get one.
something like mega upload or something. or even just a zip file in its own repository would be awsome.
Thanks.

**Comment by myron2009** [comment]
Give me your e-mail~

**Comment by SKuRGe911** [comment]
skurge@westnet.com.au

**Comment by myron2009** [comment]
I'll try to use email  ~Later ~Lat ~L
