### ISSUE TITLE
蜂鸟E200和Freedom E310内核区别

### ISSUE THREAD

**Issue by shenfanML** [SI-RISCV/e200_opensource#34]
在书《手把手教你设计CPURISC-V处理器篇》中提到
> E200开源项目也是以Freedom E310 SoC为参考蓝本，在其基础上进行二次开发称为E200配套的SOC，主要修改如下：
> 将Rocket Core替换成蜂鸟E200处理器核；
> 将TileLink总线替换成ICB总线；
请问一下，蜂鸟E200内核和Freedom E310的内核有什么区别？蜂鸟E200内核是Freedom E310内核简单的改写吗？

**Comment by hyf6661669** [comment]
FE310是SIFIVE公司设计的E31内核，蜂鸟e200是胡振波大佬设计的2级流水线内核，前者的复杂度较高功能也更多，当然功耗和面积也更大，如果想要了解E310的设计需要去看rocket-chip的源码。。

**Comment by shenfanML** [comment]
> 
> 
> FE310是SIFIVE公司设计的E31内核，蜂鸟e200是胡振波大佬设计的2级流水线内核，前者的复杂度较高功能也更多，当然功耗和面积也更大，如果想要了解E310的设计需要去看rocket-chip的源码。。

谢谢！
