### ISSUE TITLE
Can E200 SoC be implemented on Zedboard or Virtex-7?

### ISSUE THREAD

**Issue by clx7913** [SI-RISCV/e200_opensource#7]
Could it be implemented on any boards which have PL(PFGA)?

**Comment by fox6666** [comment]
hi,friends. Do you know the answers: Can e200 be implemented on Zedboard?

**Comment by fox6666** [comment]
ok, thank you!

**Comment by tangchuanchuan** [comment]
hi,friends. Do you know the answers: Can e200 be implemented on other board?

**Comment by hyf6661669** [comment]
@clx7913 

Of course you can. E200 actually doesn't consume many resources. But you must create your own .tcl and .xdc files by youselves for your FPGA board. based on your hardware. It is a bit of time-consuming.
